# Generated by Django 5.0.1 on 2025-01-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CastMember",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("DIRECTOR", "DIRECTOR"), ("ACTOR", "ACTOR")],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cast Member",
                "verbose_name_plural": "Cast Members",
                "db_table": "cast_member",
            },
        ),
    ]
